// src/gui/app.rs
use std::time::{Duration, Instant};

use eframe::egui::{
    self, Align, Color32, CornerRadius, Frame, Key, Layout, Margin, RichText,
    ScrollArea, Sense, Stroke, TextEdit, Ui, Vec2,
};
use log::info;

use element_selector::core::model::{
    AppConfig, DetailedValidationResult, ElementTab, HighlightInfo,
    HierarchyNode, Operator, PropertyFilter, SegmentValidationResult,
    ValidationResult, WindowInfo,
};
use element_selector::core::xpath;
use element_selector::core::XPathOptimizer;
use element_selector::capture;

use super::capture_overlay::CaptureOverlay;
use super::highlight;
use super::mouse_hook::{self, CaptureMode};

// ─── Palette ──────────────────────────────────────────────────────────────────
const C_TITLE_BG:  Color32 = Color32::from_rgb(30,  58, 100);
const C_TITLE_FG:  Color32 = Color32::from_rgb(226, 235, 246);
const C_SEL_BG:    Color32 = Color32::from_rgb(219, 234, 254);
const C_SEL_FG:    Color32 = Color32::from_rgb(30,  64, 175);
const C_PANEL_HDR: Color32 = Color32::from_rgb(241, 245, 249);
const C_BORDER:    Color32 = Color32::from_rgb(203, 213, 225);
const C_TARGET_FG: Color32 = Color32::from_rgb(30,  64, 175);
const C_OK:        Color32 = Color32::from_rgb(22,  163,  74);
const C_ERR:       Color32 = Color32::from_rgb(220,  38,  38);
const C_WARN:      Color32 = Color32::from_rgb(202, 138,   4);
const C_MUTED:     Color32 = Color32::from_rgb(107, 114, 128);
const C_MONO_FG:   Color32 = Color32::from_rgb(37,  99,  235);
const C_DIVIDER:   Color32 = Color32::from_rgb(220, 228, 240);
const C_CAPTURE_BG:Color32 = Color32::from_rgb(254, 252, 232); // amber-50
const C_CAPTURE_FG:Color32 = Color32::from_rgb(133,  79,  11); // amber-800

// ─── XPath 来源状态（替代双重 bool 标志）────────────────────────────────────────
#[derive(Debug, Clone)]
enum XPathSource {
    /// 由层级结构自动生成
    AutoGenerated,
    /// 经过智能优化，携带摘要信息
    Optimized(element_selector::core::OptimizationSummary),
    /// 用户手动编辑
    Manual,
}

impl XPathSource {
    fn is_auto(&self) -> bool {
        matches!(self, XPathSource::AutoGenerated)
    }
    fn optimization_summary(&self) -> Option<&element_selector::core::OptimizationSummary> {
        if let XPathSource::Optimized(s) = self { Some(s) } else { None }
    }
}

// ─── Capture state ────────────────────────────────────────────────────────────
#[derive(Debug, PartialEq)]
enum CaptureState {
    Idle,
    WaitingClick { deadline: Instant },
    Capturing,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct PersistedCapture {
    hierarchy:         Vec<HierarchyNode>,
    selected_node:     Option<usize>,
    xpath_text:        String,
    window_info:       Option<WindowInfo>,
    /// 每个节点的过滤器 enabled 状态（用户修改）
    node_filters_enabled: Vec<Vec<bool>>,
    /// 每个节点的 included 状态（用户修改）
    node_included:       Vec<bool>,
    /// 窗口过滤器状态
    window_filters_enabled: Vec<bool>,
    /// XPath 来源类型
    xpath_source_kind:   String,  // "Auto", "Optimized", "Manual"
    /// 优化摘要（如果有）
    optimization_summary: Option<OptimizationSummaryPersisted>,
}

/// 优化摘要持久化格式
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct OptimizationSummaryPersisted {
    removed_dynamic_attrs: usize,
    simplified_attrs:      usize,
    used_anchor:           bool,
}

// ─── App ──────────────────────────────────────────────────────────────────────
pub struct SelectorApp {
    element_name:      String,
    active_tab:        ElementTab,

    hierarchy:         Vec<HierarchyNode>,
    selected_node:     Option<usize>,
    window_info:       Option<WindowInfo>,
    window_filters:    Vec<PropertyFilter>,
    /// 窗口过滤器是否已为当前 window_info 初始化过
    window_filters_initialized: bool,

    #[allow(dead_code)]
    available_windows: Vec<WindowInfo>,
    #[allow(dead_code)]
    show_window_panel: bool,

    xpath_text:          String,
    window_selector:     String,
    element_xpath:       String,
    xpath_error:         Option<String>,
    /// 窗口选择器是否由用户手动编辑
    custom_window_xpath: bool,
    /// XPath 来源（替代 custom_xpath bool + optimization_summary Option）
    xpath_source:        XPathSource,
    show_simplified:     bool,

    validation:          ValidationResult,
    detailed_validation: Option<DetailedValidationResult>,
    capture_state:       CaptureState,
    overlay:             CaptureOverlay,

    status_msg:   String,
    history:      Vec<String>,
    pending_save: bool,

    config:        AppConfig,
    #[allow(dead_code)]
    countdown_str: String,

    last_mouse_move:    Option<Instant>,
    last_highlight_pos: Option<(i32, i32)>,

    node_expanded:    Vec<bool>,
    left_panel_width: f32,
    divider_dragging: bool,
}

impl SelectorApp {
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        let config: AppConfig = cc
            .storage
            .and_then(|s| {
                s.get_string("app_config")
                    .and_then(|json| serde_json::from_str(&json).ok())
            })
            .unwrap_or_default();

        let save_path = std::env::current_dir()
            .unwrap_or_default()
            .join("last_capture.json");

        let (hierarchy, selected_node, xpath_text, window_selector, element_xpath, window_info, persisted_state) =
            if save_path.exists() {
                match std::fs::read_to_string(&save_path)
                    .ok()
                    .and_then(|s| serde_json::from_str::<PersistedCapture>(&s).ok())
                {
                    Some(c) => {
                        info!("Restored {} nodes from last_capture.json", c.hierarchy.len());
                        let window_info = c.window_info.or_else(|| {
                            c.hierarchy.first().map(|node| WindowInfo {
                                title:        node.name.clone(),
                                class_name:   node.class_name.clone(),
                                process_id:   node.process_id,
                                process_name: String::new(),
                            })
                        });
                        // 恢复每个节点的状态
                        let mut hierarchy = c.hierarchy;
                        for (i, node) in hierarchy.iter_mut().enumerate() {
                            // 恢复 included 状态
                            if i < c.node_included.len() {
                                node.included = c.node_included[i];
                            }
                            // 恢复 filters enabled 状态
                            if i < c.node_filters_enabled.len() {
                                for (j, enabled) in c.node_filters_enabled[i].iter().enumerate() {
                                    if j < node.filters.len() {
                                        node.filters[j].enabled = *enabled;
                                    }
                                }
                            }
                        }
                        // 恢复 XPath 来源状态
                        let xpath_source = match c.xpath_source_kind.as_str() {
                            "Optimized" => {
                                if let Some(summary) = c.optimization_summary {
                                    XPathSource::Optimized(element_selector::core::OptimizationSummary {
                                        removed_dynamic_attrs: summary.removed_dynamic_attrs,
                                        simplified_attrs: summary.simplified_attrs,
                                        used_anchor: summary.used_anchor,
                                        anchor_description: None,
                                        compression_ratio: 0.0,
                                    })
                                } else {
                                    XPathSource::AutoGenerated
                                }
                            }
                            "Manual" => XPathSource::Manual,
                            _ => XPathSource::AutoGenerated,
                        };
                        // 重新生成 XPath（基于恢复后的 hierarchy）
                        let xpath_result = xpath::generate(&hierarchy, window_info.as_ref());
                        let xpath = format!("{}, {}", xpath_result.window_selector, xpath_result.element_xpath);
                        (hierarchy, c.selected_node, xpath, xpath_result.window_selector, xpath_result.element_xpath, window_info, (c.window_filters_enabled, xpath_source))
                    }
                    None => {
                        info!("Failed to parse last_capture.json, using mock");
                        let (h, s, x, ws, ex, wi) = Self::mock_capture();
                        (h, s, x, ws, ex, wi, (Vec::new(), XPathSource::AutoGenerated))
                    }
                }
            } else {
                info!("No last_capture.json, using mock");
                let (h, s, x, ws, ex, wi) = Self::mock_capture();
                (h, s, x, ws, ex, wi, (Vec::new(), XPathSource::AutoGenerated))
            };

        // 从 window_info 构建初始过滤器，并恢复 enabled 状态
        let (window_filters, window_filters_initialized) = if let Some(ref win) = window_info {
            let mut filters = Self::build_filters_from_info(win);
            // 恢复 enabled 状态
            for (i, enabled) in persisted_state.0.iter().enumerate() {
                if i < filters.len() {
                    filters[i].enabled = *enabled;
                }
            }
            (filters, true)
        } else {
            (Vec::new(), false)
        };

        let n = hierarchy.len();
        Self {
            element_name: String::new(),
            active_tab: ElementTab::Element,
            hierarchy,
            selected_node,
            window_info,
            window_filters,
            window_filters_initialized,
            available_windows: Vec::new(),
            show_window_panel: true,
            xpath_text,
            window_selector,
            element_xpath,
            xpath_error: None,
            custom_window_xpath: false,
            xpath_source: persisted_state.1,
            show_simplified: config.show_simplified,
            validation: ValidationResult::Idle,
            detailed_validation: None,
            capture_state: CaptureState::Idle,
            overlay: CaptureOverlay::new(),
            status_msg: "就绪 — 按 F4 开始捕获元素".to_string(),
            history: config.last_xpaths.clone(),
            pending_save: false,
            config,
            countdown_str: String::new(),
            last_mouse_move: None,
            last_highlight_pos: None,
            node_expanded: vec![true; n],
            left_panel_width: 300.0,
            divider_dragging: false,
        }
    }

    fn mock_capture() -> (Vec<HierarchyNode>, Option<usize>, String, String, String, Option<WindowInfo>) {
        let result = capture::mock();
        let window_info = result.window_info.clone();
        let xpath_result = xpath::generate(&result.hierarchy, window_info.as_ref());
        let xpath = format!("{}, {}", xpath_result.window_selector, xpath_result.element_xpath);
        (result.hierarchy, Some(3), xpath, xpath_result.window_selector, xpath_result.element_xpath, window_info)
    }

    fn save_to_file(&self) {
        if self.hierarchy.is_empty() { return; }
        let path = std::env::current_dir().unwrap_or_default().join("last_capture.json");
        let data = self.build_persisted_capture();
        if let Ok(json) = serde_json::to_string_pretty(&data) {
            let _ = std::fs::write(&path, json);
            info!("Saved capture to {}", path.display());
        }
    }

    /// 构建 PersistedCapture（包含完整的用户状态）
    fn build_persisted_capture(&self) -> PersistedCapture {
        // 提取每个节点的过滤器 enabled 状态
        let node_filters_enabled: Vec<Vec<bool>> = self.hierarchy.iter()
            .map(|node| node.filters.iter().map(|f| f.enabled).collect())
            .collect();
        // 提取每个节点的 included 状态
        let node_included: Vec<bool> = self.hierarchy.iter().map(|node| node.included).collect();
        // 提取窗口过滤器 enabled 状态
        let window_filters_enabled: Vec<bool> = self.window_filters.iter().map(|f| f.enabled).collect();
        // XPath 来源类型
        let xpath_source_kind = match &self.xpath_source {
            XPathSource::AutoGenerated => "Auto",
            XPathSource::Optimized(_) => "Optimized",
            XPathSource::Manual => "Manual",
        }.to_string();
        // 优化摘要
        let optimization_summary = self.xpath_source.optimization_summary().map(|s| OptimizationSummaryPersisted {
            removed_dynamic_attrs: s.removed_dynamic_attrs,
            simplified_attrs: s.simplified_attrs,
            used_anchor: s.used_anchor,
        });

        PersistedCapture {
            hierarchy: self.hierarchy.clone(),
            selected_node: self.selected_node,
            xpath_text: self.xpath_text.clone(),
            window_info: self.window_info.clone(),
            node_filters_enabled,
            node_included,
            window_filters_enabled,
            xpath_source_kind,
            optimization_summary,
        }
    }

    // ── XPath helpers ─────────────────────────────────────────────────────────

    fn rebuild_xpath(&mut self) {
        // 只有 AutoGenerated 状态才自动重建，Optimized / Manual 保留当前内容
        if !self.xpath_source.is_auto() { return; }

        let window_selector = self.build_window_selector_from_info();
        let element_xpath = if self.show_simplified {
            xpath::generate_simplified_elements(&self.hierarchy)
        } else {
            xpath::generate_elements(&self.hierarchy)
        };

        self.window_selector = window_selector;
        self.element_xpath   = element_xpath;
        self.xpath_text      = format!("{}, {}", self.window_selector, self.element_xpath);
        self.xpath_error     = xpath::lint(&self.xpath_text);
        self.validation      = ValidationResult::Idle;
    }

    /// 从 window_info 构建窗口选择器字符串
    fn build_window_selector_from_info(&self) -> String {
        let Some(ref win) = self.window_info else {
            return "Window".to_string();
        };
        let mut conditions = Vec::new();
        if !win.class_name.is_empty() {
            conditions.push(format!("@ClassName='{}'", win.class_name));
        }
        if !win.title.is_empty() {
            conditions.push(format!("@Name='{}'", win.title));
        }
        if !win.process_name.is_empty() {
            conditions.push(format!("@ProcessName='{}'", win.process_name));
        }
        if conditions.is_empty() {
            "Window".to_string()
        } else {
            format!("Window[{}]", conditions.join(" and "))
        }
    }

    /// 从 WindowInfo 构建 PropertyFilter 列表（纯函数，不依赖 &mut self）
    fn build_filters_from_info(win: &WindowInfo) -> Vec<PropertyFilter> {
        vec![
            PropertyFilter::new("Name",        &win.title),
            PropertyFilter::new("ClassName",   &win.class_name),
            PropertyFilter::new("ProcessName", &win.process_name),
        ]
    }

    /// 初始化窗口过滤器（仅在 window_info 变更时调用，而非每帧 draw）
    fn init_window_filters(&mut self) {
        if let Some(ref win) = self.window_info {
            self.window_filters             = Self::build_filters_from_info(win);
            self.window_filters_initialized = true;
            self.custom_window_xpath        = false;
        }
    }

    /// 从窗口过滤器重新生成窗口选择器
    fn rebuild_window_selector(&mut self) {
        let predicates: Vec<String> = self.window_filters
            .iter()
            .filter_map(|f| f.predicate())
            .collect();
        self.window_selector = if predicates.is_empty() {
            "Window".to_string()
        } else {
            format!("Window[{}]", predicates.join(" and "))
        };
        self.xpath_text  = format!("{}, {}", self.window_selector, self.element_xpath);
        self.xpath_error = xpath::lint(&self.xpath_text);
        self.validation  = ValidationResult::Idle;
    }

    fn push_history(&mut self) {
        let x = self.xpath_text.clone();
        if x.is_empty() { return; }
        self.history.retain(|h| h != &x);
        self.history.insert(0, x);
        self.history.truncate(20);
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    fn start_capture(&mut self) {
        self.capture_state = CaptureState::WaitingClick {
            deadline: Instant::now() + Duration::from_secs(30),
        };
        self.status_msg = "请点击目标控件（Esc 取消）…".to_string();
        mouse_hook::activate_capture(true);
        self.overlay.show();
    }

    fn cancel_capture(&mut self, ctx: &egui::Context) {
        highlight::hide();
        mouse_hook::deactivate_capture();
        self.overlay.hide();
        self.capture_state = CaptureState::Idle;
        self.status_msg    = "捕获已取消".to_string();
        ctx.set_cursor_icon(egui::CursorIcon::Default);
    }

    fn finish_capture_at(&mut self, x: i32, y: i32, mode: CaptureMode, ctx: &egui::Context) {
        highlight::hide();
        mouse_hook::deactivate_capture();
        self.overlay.hide();
        self.capture_state = CaptureState::Capturing;

        if let CaptureMode::Batch = mode {
            self.status_msg = "批量捕获模式：正在分析相似元素…".to_string();
        }

        let result = capture::capture_at(x, y);
        if let Some(err) = &result.error {
            self.status_msg = format!("捕获失败: {}", err);
        } else {
            let window_idx = Self::find_window_idx(&result);

            info!("捕获 hierarchy 共 {} 个节点:", result.hierarchy.len());
            for (i, n) in result.hierarchy.iter().enumerate() {
                info!("  [{}] {} class='{}' name='{}' pid={}", i, n.control_type, n.class_name, n.name, n.process_id);
            }
            if let Some(ref win) = result.window_info {
                info!("Window info: class='{}', name='{}', process='{}', pid={}",
                      win.class_name, win.title, win.process_name, win.process_id);
            }
            info!("窗口节点定位: window_idx = {}", window_idx);

            let element_hierarchy: Vec<HierarchyNode> = if window_idx < result.hierarchy.len() - 1 {
                result.hierarchy[window_idx + 1..].to_vec()
            } else {
                Vec::new()
            };

            let n = element_hierarchy.len();
            self.selected_node = n.checked_sub(1);
            self.window_info   = result.window_info.clone();

            // window_info 变更时同步初始化过滤器
            self.init_window_filters();

            let window_hint = result.window_info
                .as_ref()
                .map(|w| format!(" [窗口: {}]", w.title))
                .unwrap_or_default();
            self.status_msg = format!(
                "已捕获 {} 层层级 — 坐标 ({}, {}){}",
                n, result.cursor_x, result.cursor_y, window_hint
            );

            self.node_expanded = vec![true; n];
            self.hierarchy     = element_hierarchy;
        }

        self.capture_state = CaptureState::Idle;
        self.xpath_source  = XPathSource::AutoGenerated;
        self.validation    = ValidationResult::Idle;
        self.rebuild_xpath();
        self.pending_save = true;
        self.save_to_file();
        info!("capture done: {}", self.xpath_text);

        ctx.set_cursor_icon(egui::CursorIcon::Default);
        ctx.send_viewport_cmd(egui::ViewportCommand::Focus);
    }

    /// 从 capture 结果中定位窗口节点索引
    fn find_window_idx(result: &capture::CaptureResult) -> usize {
        if let Some(ref win) = result.window_info {
            result.hierarchy.iter()
                .position(|n| n.class_name == win.class_name && n.process_id == win.process_id)
                .or_else(|| result.hierarchy.iter().position(|n| n.process_id == win.process_id))
                .or_else(|| result.hierarchy.iter().position(|n| n.control_type == "Window"))
                .unwrap_or(0)
        } else {
            result.hierarchy.iter()
                .position(|n| n.control_type == "Window")
                .unwrap_or(0)
        }
    }

    fn do_validate(&mut self) {
        self.xpath_error = xpath::lint(&self.xpath_text);
        if let Some(err) = &self.xpath_error {
            self.status_msg = format!("XPath 语法错误: {}", err);
            return;
        }
        self.validation = ValidationResult::Running;

        let detailed_result = capture::validate_selector_and_xpath_detailed(
            &self.window_selector,
            &self.element_xpath,
            &self.hierarchy,
        );
        self.detailed_validation = Some(detailed_result.clone());
        self.validation = detailed_result.overall.clone();

        if let ValidationResult::Found { ref first_rect, .. } = detailed_result.overall {
            if let Some(r) = first_rect { highlight::flash(r, 1200); }
        }
        self.status_msg = match &detailed_result.overall {
            ValidationResult::Found { count, .. } =>
                format!("校验通过 ✔ — 找到 {} 个匹配元素 (总用时: {}ms)", count, detailed_result.total_duration_ms),
            ValidationResult::NotFound =>
                format!("校验失败 — 未找到匹配元素 (总用时: {}ms)", detailed_result.total_duration_ms),
            ValidationResult::Error(e) => format!("校验错误: {}", e),
            _ => String::new(),
        };
        self.push_history();
    }

    fn do_optimize(&mut self) {
        if self.hierarchy.is_empty() {
            self.status_msg = "没有元素可优化".to_string();
            return;
        }

        info!("[智能优化] 开始优化，节点数: {}", self.hierarchy.len());
        info!("[智能优化] 优化前 XPath: {}", self.element_xpath);

        let optimizer = XPathOptimizer::new();
        let result    = optimizer.optimize(&self.hierarchy);

        info!("[智能优化] 完成：移除 {} 个动态属性，简化 {} 个属性",
            result.summary.removed_dynamic_attrs,
            result.summary.simplified_attrs);

        // 更新 hierarchy
        self.hierarchy = result.optimized_hierarchy.clone();

        // 通过临时设为 AutoGenerated 来复用 rebuild_xpath，然后标记为 Optimized
        // 注意：这里不使用 trick，而是直接调用内部逻辑
        let window_selector = self.build_window_selector_from_info();
        let element_xpath = if self.show_simplified {
            xpath::generate_simplified_elements(&self.hierarchy)
        } else {
            xpath::generate_elements(&self.hierarchy)
        };
        self.window_selector = window_selector;
        self.element_xpath   = element_xpath;
        self.xpath_text      = format!("{}, {}", self.window_selector, self.element_xpath);
        self.xpath_error     = xpath::lint(&self.xpath_text);
        self.validation      = ValidationResult::Idle;

        // 标记为已优化状态
        self.xpath_source = XPathSource::Optimized(result.summary.clone());

        let summary = &result.summary;
        self.status_msg = format!(
            "智能优化完成：移除 {} 个动态属性，简化 {} 个属性{}",
            summary.removed_dynamic_attrs,
            summary.simplified_attrs,
            if summary.used_anchor {
                format!("，使用锚点 {}", summary.anchor_description.as_ref().unwrap_or(&String::new()))
            } else {
                String::new()
            }
        );

        info!("[智能优化] 优化后 XPath: {}", self.element_xpath);
        self.do_validate();
        self.save_to_file();
    }

    fn do_confirm_and_close(&mut self, ctx: &egui::Context) {
        // 1. 语法检查
        if let Some(err) = xpath::lint(&self.xpath_text) {
            self.status_msg = format!("⚠ XPath 语法错误，请先修正：{}", err);
            return;
        }
        // 2. 若未校验过，先自动校验
        if matches!(self.validation, ValidationResult::Idle) {
            self.do_validate();
        }
        // 3. 校验失败时阻止关闭
        match &self.validation {
            ValidationResult::NotFound => {
                self.status_msg = "校验未通过，元素未找到。如需强制保存请先点击取消".to_string();
                return;
            }
            ValidationResult::Error(e) => {
                self.status_msg = format!("校验出错：{}，请检查后再确定", e);
                return;
            }
            _ => {}
        }
        self.push_history();
        self.save_to_file();
        ctx.send_viewport_cmd(egui::ViewportCommand::Close);
    }

    fn highlight_element_at(&mut self, x: i32, y: i32) {
        let result = capture::capture_at(x, y);
        if result.error.is_none() {
            if let Some(last) = result.hierarchy.last() {
                let highlight_info = HighlightInfo::new(last.rect.clone(), &last.control_type);
                highlight::update_highlight(&highlight_info);
            }
        }
    }

    // ── Panels ────────────────────────────────────────────────────────────────

    fn draw_titlebar(&self, ui: &mut Ui) {
        egui::Panel::top("titlebar")
            .exact_size(32.0)
            .frame(Frame::NONE.fill(C_TITLE_BG))
            .show_inside(ui, |ui| {
                ui.horizontal_centered(|ui| {
                    ui.add_space(12.0);
                    ui.label(
                        RichText::new("🔍  Windows 元素选择器")
                            .color(C_TITLE_FG)
                            .size(13.5)
                            .strong(),
                    );
                    ui.with_layout(Layout::right_to_left(Align::Center), |ui| {
                        ui.add_space(12.0);
                        if !self.history.is_empty() {
                            ui.label(
                                RichText::new(format!("历史: {}", self.history.len()))
                                    .color(Color32::from_gray(150))
                                    .size(10.5),
                            );
                        }
                    });
                });
            });
    }

    /// 顶部控制栏：名称 + 捕获 + 校验
    fn draw_top_bar(&mut self, ui: &mut Ui) {
        egui::Panel::top("top_bar")
            .exact_size(44.0)
            .frame(
                Frame::NONE
                    .fill(Color32::from_gray(248))
                    .inner_margin(Margin::symmetric(12, 8))
                    .stroke(Stroke::new(1.0, C_BORDER)),
            )
            .show_inside(ui, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new("元素名称:").color(C_MUTED).size(11.5));
                    ui.add_space(4.0);
                    ui.add(
                        TextEdit::singleline(&mut self.element_name)
                            .desired_width(160.0)
                            .hint_text("输入名称便于速查"),
                    );

                    ui.with_layout(Layout::right_to_left(Align::Center), |ui| {
                        // 校验按钮
                        let val_label = self.validation.label();
                        let val_color = match &self.validation {
                            ValidationResult::Found { .. } => C_OK,
                            ValidationResult::NotFound | ValidationResult::Error(_) => C_ERR,
                            _ => Color32::from_gray(50),
                        };
                        if ui.add(
                            egui::Button::new(RichText::new(&val_label).color(val_color).size(12.0))
                                .stroke(Stroke::new(1.0, val_color))
                                .min_size(Vec2::new(100.0, 28.0)),
                        ).on_hover_text("F7 — 校验当前 XPath 是否有效").clicked() {
                            self.do_validate();
                        }

                        ui.add_space(8.0);

                        // 捕获 / 取消捕获 按钮
                        match &self.capture_state {
                            CaptureState::WaitingClick { deadline } => {
                                let s = deadline.saturating_duration_since(Instant::now()).as_secs();
                                if ui.add(
                                    egui::Button::new(
                                        RichText::new(format!("取消捕获 ({}s)", s))
                                            .color(C_WARN)
                                            .size(12.0),
                                    )
                                    .stroke(Stroke::new(1.0, C_WARN))
                                    .min_size(Vec2::new(120.0, 28.0)),
                                ).on_hover_text("点击或按 Esc 取消").clicked() {
                                    self.cancel_capture(ui.ctx());
                                }
                            }
                            CaptureState::Capturing => {
                                ui.add(
                                    egui::Button::new(RichText::new("捕获中…").color(C_WARN).size(12.0))
                                        .min_size(Vec2::new(100.0, 28.0)),
                                );
                            }
                            CaptureState::Idle => {
                                if ui.add(
                                    egui::Button::new(
                                        RichText::new("重新捕获 F4")
                                            .color(Color32::from_gray(50))
                                            .size(12.0),
                                    )
                                    .min_size(Vec2::new(100.0, 28.0)),
                                ).on_hover_text("F4 — 点击屏幕控件进行捕获").clicked() {
                                    self.start_capture();
                                }
                            }
                        }
                    });
                });
            });
    }

    /// 捕获状态横幅（仅在 WaitingClick 时显示）
    fn draw_capture_banner(&self, ui: &mut Ui) {
        if !matches!(self.capture_state, CaptureState::WaitingClick { .. }) {
            return;
        }
        egui::Panel::top("capture_banner")
            .exact_size(26.0)
            .frame(
                Frame::NONE
                    .fill(C_CAPTURE_BG)
                    .stroke(Stroke::new(1.0, Color32::from_rgb(253, 230, 138))),
            )
            .show_inside(ui, |ui| {
                ui.horizontal_centered(|ui| {
                    ui.add_space(12.0);
                    ui.label(
                        RichText::new("⏳  请点击目标控件 — 按 Esc 或顶栏按钮取消")
                            .color(C_CAPTURE_FG)
                            .size(11.5),
                    );
                });
            });
    }

    /// 底部面板：XPath 预览 + 状态 + 确定/取消（合并为单一 Panel）
    fn draw_bottom_panel(&mut self, ui: &mut Ui) {
        egui::Panel::bottom("bottom_panel")
            .frame(
                Frame::NONE
                    .fill(Color32::from_gray(245))
                    .inner_margin(Margin::symmetric(12, 8))
                    .stroke(Stroke::new(1.0, C_BORDER)),
            )
            .show_inside(ui, |ui| {
                // ── XPath 预览区 ─────────────────────────────────────────────
                self.draw_xpath_preview_content(ui);

                ui.add_space(6.0);

                // ── 状态消息 + 操作按钮 ────────────────────────────────────────
                ui.horizontal(|ui| {
                    // 状态消息
                    let msg_color = match &self.validation {
                        ValidationResult::Found { .. }              => C_OK,
                        ValidationResult::NotFound | ValidationResult::Error(_) => C_ERR,
                        ValidationResult::Running                   => C_WARN,
                        _ => C_MUTED,
                    };
                    ui.label(RichText::new(&self.status_msg).color(msg_color).size(11.5));

                    ui.with_layout(Layout::right_to_left(Align::Center), |ui| {
                        // 确定按钮（校验通过后变绿）
                        let (confirm_label, confirm_fill) = match &self.validation {
                            ValidationResult::Found { .. } =>
                                ("✔ 确定（已校验）", C_OK),
                            _ =>
                                ("确定", Color32::from_gray(160)),
                        };
                        if ui.add(
                            egui::Button::new(
                                RichText::new(confirm_label).color(Color32::WHITE).size(12.0),
                            )
                            .fill(confirm_fill)
                            .min_size(Vec2::new(110.0, 30.0)),
                        ).on_hover_text("保存并关闭（未校验时会先自动校验）").clicked() {
                            self.do_confirm_and_close(ui.ctx());
                        }

                        ui.add_space(6.0);

                        // 取消按钮（强制关闭，不做校验）
                        if ui.add(
                            egui::Button::new(
                                RichText::new("取消").color(Color32::from_gray(50)).size(12.0),
                            )
                            .min_size(Vec2::new(70.0, 30.0)),
                        ).on_hover_text("放弃本次操作并关闭").clicked() {
                            self.save_to_file();
                            ui.ctx().send_viewport_cmd(egui::ViewportCommand::Close);
                        }

                        ui.add_space(8.0);

                        // 历史记录下拉（右侧辅助功能）
                        if !self.history.is_empty() {
                            egui::ComboBox::from_id_salt("history_combo")
                                .selected_text(format!("历史 ({})", self.history.len()))
                                .width(90.0)
                                .show_ui(ui, |ui| {
                                    let mut chosen = None;
                                    for (i, h) in self.history.iter().enumerate() {
                                        let label = if h.len() > 40 {
                                            format!("{}…", &h[..40])
                                        } else {
                                            h.clone()
                                        };
                                        if ui.selectable_label(false, label).clicked() {
                                            chosen = Some(i);
                                        }
                                    }
                                    if let Some(i) = chosen {
                                        self.xpath_text      = self.history[i].clone();
                                        self.xpath_source    = XPathSource::Manual;
                                        self.xpath_error     = xpath::lint(&self.xpath_text);
                                        self.validation      = ValidationResult::Idle;
                                    }
                                });
                        }
                    });
                });
            });
    }

    /// XPath 预览内容（根据标签页切换）
    fn draw_xpath_preview_content(&mut self, ui: &mut Ui) {
        Frame::NONE
            .fill(Color32::from_gray(252))
            .inner_margin(Margin::symmetric(10, 6))
            .stroke(Stroke::new(1.0, C_BORDER))
            .corner_radius(CornerRadius::same(4))
            .show(ui, |ui| {
                match self.active_tab {
                    ElementTab::Element      => self.draw_element_xpath_content(ui),
                    ElementTab::WindowElement => self.draw_window_xpath_content(ui),
                }
            });
    }

    /// 元素模式：XPath 预览内容
    fn draw_element_xpath_content(&mut self, ui: &mut Ui) {
        ui.horizontal(|ui| {
            ui.label(RichText::new("元素 XPath:").color(C_MUTED).size(11.0));
            ui.add_space(4.0);

            if ui.small_button("复制").on_hover_text("复制元素 XPath").clicked() {
                ui.ctx().copy_text(self.element_xpath.clone());
                self.status_msg = "元素 XPath 已复制到剪贴板".to_string();
            }

            if ui.small_button("智能优化").on_hover_text("自动优化 XPath，移除动态属性，使用锚点定位").clicked() {
                self.do_optimize();
            }

            // 重置：仅在 Optimized 或 Manual 状态下显示
            if !self.xpath_source.is_auto() {
                if ui.small_button("重置").on_hover_text("恢复为自动生成的 XPath").clicked() {
                    self.xpath_source = XPathSource::AutoGenerated;
                    self.rebuild_xpath();
                }
            }

            // 优化摘要标签
            if let Some(summary) = self.xpath_source.optimization_summary() {
                ui.add_space(4.0);
                ui.label(
                    RichText::new(format!(
                        "已优化：移除 {} / 简化 {} {}",
                        summary.removed_dynamic_attrs,
                        summary.simplified_attrs,
                        if summary.used_anchor { "· 锚点" } else { "" }
                    ))
                    .color(C_OK)
                    .size(10.0),
                );
            }

            // 手动编辑标签
            if matches!(self.xpath_source, XPathSource::Manual) {
                ui.add_space(4.0);
                ui.label(RichText::new("[手动编辑]").color(C_WARN).size(10.0));
            }

            if let Some(err) = &self.xpath_error {
                ui.add_space(4.0);
                ui.label(RichText::new(format!("⚠ {}", err)).color(C_ERR).size(10.5));
            }
        });

        let edit_resp = ui.add(
            TextEdit::multiline(&mut self.element_xpath)
                .font(egui::TextStyle::Monospace)
                .desired_rows(2)
                .desired_width(ui.available_width())
                .hint_text("/ControlType[@Attr='val']")
                .text_color(C_MONO_FG),
        );
        if edit_resp.changed() {
            self.xpath_source = XPathSource::Manual;
            self.xpath_text   = format!("{}, {}", self.window_selector, self.element_xpath);
            self.xpath_error  = xpath::lint(&self.xpath_text);
            self.validation   = ValidationResult::Idle;
        }
    }

    /// 窗口元素模式：XPath 预览内容
    fn draw_window_xpath_content(&mut self, ui: &mut Ui) {
        ui.horizontal(|ui| {
            ui.label(RichText::new("窗口选择器:").color(C_MUTED).size(11.0));
            ui.add_space(4.0);

            if ui.small_button("复制").on_hover_text("复制窗口选择器").clicked() {
                ui.ctx().copy_text(self.window_selector.clone());
                self.status_msg = "窗口选择器已复制到剪贴板".to_string();
            }

            if self.custom_window_xpath {
                if ui.small_button("重置").on_hover_text("回到自动生成的窗口选择器").clicked() {
                    self.custom_window_xpath = false;
                    self.init_window_filters();
                    self.rebuild_xpath();
                }
                ui.label(RichText::new("[自定义]").color(C_WARN).size(10.0));
            }
        });

        let edit_resp = ui.add(
            TextEdit::multiline(&mut self.window_selector)
                .font(egui::TextStyle::Monospace)
                .desired_rows(2)
                .desired_width(ui.available_width())
                .hint_text("Window[@Name='...' and @ClassName='...']")
                .text_color(C_MONO_FG),
        );
        if edit_resp.changed() {
            self.custom_window_xpath = true;
            self.xpath_text  = format!("{}, {}", self.window_selector, self.element_xpath);
            self.xpath_error = xpath::lint(&self.xpath_text);
            self.validation  = ValidationResult::Idle;
        }
    }

    // ── Left panel ────────────────────────────────────────────────────────────

    fn draw_left_panel(&mut self, ui: &mut Ui) {
        match self.active_tab {
            ElementTab::Element       => self.draw_element_tree(ui),
            ElementTab::WindowElement => self.draw_window_tree(ui),
        }
    }

    fn draw_element_tree(&mut self, ui: &mut Ui) {
        panel_header(ui, "📂  元素层级结构");
        ui.add_space(2.0);

        if self.node_expanded.len() != self.hierarchy.len() {
            self.node_expanded.resize(self.hierarchy.len(), true);
        }

        ScrollArea::vertical()
            .id_salt("tree_scroll")
            .auto_shrink([false; 2])
            .show(ui, |ui| {
                let n = self.hierarchy.len();
                if n == 0 {
                    ui.label(RichText::new("尚未捕获元素").color(C_MUTED).italics());
                    return;
                }

                ui.spacing_mut().item_spacing.y = 0.0;

                let validation_segments     = self.detailed_validation.as_ref().map(|d| &d.segments);
                let show_validation_details = self.config.show_validation_details;
                let validation_result        = Some(&self.validation);

                let included_changed = Self::draw_tree_flat(
                    ui,
                    &mut self.hierarchy,
                    &mut self.selected_node,
                    validation_segments,
                    show_validation_details,
                    validation_result,
                );

                if included_changed {
                    if matches!(self.xpath_source, XPathSource::Optimized(_)) {
                        self.do_optimize();
                    } else {
                        self.xpath_source = XPathSource::AutoGenerated;
                        self.rebuild_xpath();
                    }
                }
                ui.add_space(12.0);
            });
    }

    fn draw_window_tree(&mut self, ui: &mut Ui) {
        panel_header(ui, "🪟  窗口信息");
        ui.add_space(4.0);

        if let Some(ref win) = self.window_info {
            egui::Frame::NONE
                .fill(Color32::from_rgb(239, 246, 255))
                .corner_radius(CornerRadius::same(4))
                .inner_margin(Margin::symmetric(10, 8))
                .show(ui, |ui| {
                    ui.vertical(|ui| {
                        prop_row(ui, "标题",  &win.title);
                        prop_row(ui, "类名",  if win.class_name.is_empty()   { "(空)" } else { &win.class_name });
                        prop_row(ui, "进程名", if win.process_name.is_empty() { "(空)" } else { &win.process_name });
                        prop_row(ui, "进程ID", &win.process_id.to_string());
                    });
                });
        } else {
            ui.label(RichText::new("尚未选择窗口").color(C_MUTED).italics());
            ui.add_space(4.0);
            ui.label(RichText::new("请先捕获元素").color(C_MUTED).size(10.5));
        }
    }

    /// 平面列表形式的元素层级树
    /// 注意：移除了已废弃的 _expanded 参数，折叠逻辑由外层 node_expanded 管理
    fn draw_tree_flat(
        ui: &mut Ui,
        hierarchy: &mut Vec<HierarchyNode>,
        selected_node: &mut Option<usize>,
        validation_segments: Option<&Vec<SegmentValidationResult>>,
        show_validation_details: bool,
        validation_result: Option<&ValidationResult>,
    ) -> bool {
        let n = hierarchy.len();
        let mut included_changed = false;

        for idx in 0..n {
            let is_target = idx == n - 1;
            let is_sel    = *selected_node == Some(idx);

            let label_text   = hierarchy[idx].tree_label();
            let node_included = hierarchy[idx].included;
            let icon = if is_target { "🎯" } else { "" };
            let label_color = if is_target        { C_TARGET_FG }
                              else if is_sel       { C_SEL_FG }
                              else if !node_included { C_MUTED }
                              else                  { Color32::from_gray(35) };

            let validation_marker = if show_validation_details {
                validation_segments
                    .and_then(|segs| segs.get(idx))
                    .map(|seg| {
                        if seg.matched {
                            format!(" ✅ {}ms", seg.duration_ms)
                        } else {
                            format!(" ❌ {}ms", seg.duration_ms)
                        }
                    })
                    .unwrap_or_default()
            } else {
                String::new()
            };

            let header_text = RichText::new(format!("{} {}{}", icon, label_text, validation_marker))
                .size(12.0)
                .color(label_color)
                .strong_if(is_sel || is_target);

            let row_bg = if is_sel { C_SEL_BG } else { Color32::TRANSPARENT };

            egui::Frame::NONE
                .fill(row_bg)
                .inner_margin(Margin::symmetric(2, 1))
                .show(ui, |ui| {
                    ui.horizontal(|ui| {
                        let cb_resp = ui.checkbox(&mut hierarchy[idx].included, "");
                        if cb_resp.changed() { included_changed = true; }
                        cb_resp.on_hover_text(if hierarchy[idx].included {
                            "已包含在 XPath 中 — 取消勾选将排除此节点"
                        } else {
                            "已排除 — 勾选将包含在 XPath 中"
                        });

                        let resp = ui.add(
                            egui::Label::new(header_text)
                                .sense(Sense::click_and_drag())
                                .truncate(),
                        );
                        if resp.clicked() {
                            *selected_node = Some(idx);
                        }

                        resp.context_menu(|ui| {
                            Self::node_context_menu(ui, hierarchy, idx, selected_node, validation_result);
                        });

                        resp.on_hover_ui(|ui| {
                            node_tooltip(ui, &hierarchy[idx]);
                        });
                    });
                });
        }

        included_changed
    }

    /// 右键菜单：只提供操作，不放提示语
    fn node_context_menu(
        ui: &mut Ui,
        hierarchy: &mut Vec<HierarchyNode>,
        idx: usize,
        selected_node: &mut Option<usize>,
        validation_result: Option<&ValidationResult>,
    ) {
        let included = hierarchy[idx].included;

        if ui.button(if included { "⊖ 从 XPath 中排除此节点" } else { "⊕ 将此节点加入 XPath" }).clicked() {
            hierarchy[idx].included = !included;
            ui.close();
        }

        ui.separator();

        // 高亮逻辑改进：根据校验状态决定使用哪个 rect
        // - 校验成功：使用实际找到的元素 rect（更准确）
        // - 校验失败/未校验：使用捕获时的 rect，但提示用户
        let highlight_label = match validation_result {
            Some(ValidationResult::Found { .. }) => "🔍 高亮显示此元素（校验位置）",
            Some(ValidationResult::NotFound) => "🔍 高亮显示此元素（捕获位置⚠）",
            Some(ValidationResult::Error(_)) => "🔍 高亮显示此元素（捕获位置⚠）",
            _ => "🔍 高亮显示此元素（捕获位置）",
        };        
        if ui.button(highlight_label).clicked() {
            // 校验成功时，优先使用校验结果的 rect
            let rect_to_use = match validation_result {
                Some(ValidationResult::Found { first_rect: Some(r), .. }) => r.clone(),
                _ => hierarchy[idx].rect.clone(),  // 校验失败或未校验，使用捕获时的 rect
            };
            let info = HighlightInfo::new(rect_to_use, &hierarchy[idx].control_type);
            highlight::flash_with_info(&info, 1500);
            ui.close();
        }

        if ui.button("📋 复制此节点 XPath 片段").clicked() {
            ui.ctx().copy_text(hierarchy[idx].xpath_segment());
            ui.close();
        }

        ui.separator();

        if ui.button("选中此节点").clicked() {
            *selected_node = Some(idx);
            ui.close();
        }
    }

    // ── Right panel ───────────────────────────────────────────────────────────

    fn draw_right_panel(&mut self, ui: &mut Ui) {
        match self.active_tab {
            ElementTab::Element       => self.draw_element_properties(ui),
            ElementTab::WindowElement => self.draw_window_properties(ui),
        }
        self.draw_validation_details(ui);
    }

    fn draw_element_properties(&mut self, ui: &mut Ui) {
        panel_header(ui, "⚙  元素属性");

        ScrollArea::vertical()
            .id_salt("prop_scroll")
            .auto_shrink([false; 2])
            .show(ui, |ui| {
                let Some(sel_idx) = self.selected_node else {
                    ui.add_space(24.0);
                    ui.label(RichText::new("← 点击左侧节点查看属性").color(C_MUTED).italics());
                    return;
                };
                if sel_idx >= self.hierarchy.len() { return; }

                // 节点摘要
                {
                    let node = &self.hierarchy[sel_idx];
                    egui::Frame::NONE
                        .fill(Color32::from_rgb(239, 246, 255))
                        .corner_radius(CornerRadius::same(4))
                        .inner_margin(Margin::symmetric(10, 6))
                        .show(ui, |ui| {
                            ui.horizontal(|ui| {
                                ui.label(RichText::new("控件类型").color(C_MUTED).size(11.0));
                                ui.add_space(6.0);
                                ui.label(RichText::new(&node.control_type).color(C_TARGET_FG).strong().size(13.0));
                                if node.rect.width > 0 {
                                    ui.add_space(12.0);
                                    ui.label(
                                        RichText::new(format!(
                                            "{}×{}  @({},{})",
                                            node.rect.width, node.rect.height,
                                            node.rect.x, node.rect.y,
                                        ))
                                        .color(C_MUTED).size(10.5),
                                    );
                                }
                                if node.process_id > 0 {
                                    ui.label(
                                        RichText::new(format!("pid:{}", node.process_id))
                                            .color(C_MUTED).size(10.5),
                                    );
                                }
                            });
                        });
                }

                ui.add_space(6.0);

                // 属性列表表头
                egui::Frame::NONE
                    .fill(C_PANEL_HDR)
                    .inner_margin(Margin::symmetric(4, 2))
                    .stroke(Stroke::new(0.5, C_BORDER))
                    .show(ui, |ui| {
                        ui.horizontal(|ui| {
                            ui.add_space(22.0);
                            col_label(ui, "属性名", 100.0);
                            col_label(ui, "运算符",  80.0);
                            col_label(ui, "值",       0.0);
                        });
                    });

                ui.add_space(2.0);

                let filter_count = self.hierarchy[sel_idx].filters.len();
                let mut dirty = false;
                for fi in 0..filter_count {
                    let row_color = if fi % 2 == 0 {
                        Color32::from_rgb(252, 252, 255)
                    } else {
                        Color32::from_rgb(245, 247, 253)
                    };

                    egui::Frame::NONE
                        .fill(row_color)
                        .inner_margin(Margin::symmetric(4, 1))
                        .show(ui, |ui| {
                            let filter = &mut self.hierarchy[sel_idx].filters[fi];
                            ui.horizontal(|ui| {
                                if ui.checkbox(&mut filter.enabled, "").changed() { dirty = true; }

                                ui.add_sized(
                                    Vec2::new(100.0, 20.0),
                                    egui::Label::new(RichText::new(&filter.name.clone()).size(12.0)),
                                );

                                let old_op = filter.operator.clone();
                                egui::ComboBox::from_id_salt(format!("op_{}_{}", sel_idx, fi))
                                    .selected_text(filter.operator.label())
                                    .width(76.0)
                                    .show_ui(ui, |ui| {
                                        for op in Operator::all() {
                                            ui.selectable_value(&mut filter.operator, op.clone(), op.label());
                                        }
                                    });
                                if filter.operator != old_op { dirty = true; }

                                if ui.add(
                                    TextEdit::singleline(&mut filter.value)
                                        .desired_width(ui.available_width() - 4.0)
                                        .font(egui::TextStyle::Monospace)
                                        .hint_text("—"),
                                ).changed() {
                                    filter.enabled = !filter.value.is_empty();
                                    dirty = true;
                                }
                            });
                        });
                }
                if dirty {
                    self.xpath_source = XPathSource::AutoGenerated;
                    self.rebuild_xpath();
                }

                ui.add_space(8.0);
                ui.separator();
                ui.add_space(4.0);

                // 本节点 XPath 片段预览
                ui.label(RichText::new("本节点 XPath 片段:").color(C_MUTED).size(11.0));
                ui.add_space(2.0);
                let seg = self.hierarchy[sel_idx].xpath_segment();
                egui::Frame::NONE
                    .fill(Color32::from_rgb(248, 250, 252))
                    .stroke(Stroke::new(0.5, C_BORDER))
                    .corner_radius(CornerRadius::same(4))
                    .inner_margin(Margin::symmetric(8, 4))
                    .show(ui, |ui| {
                        ui.label(
                            RichText::new(&seg)
                                .font(egui::FontId::monospace(11.0))
                                .color(C_MONO_FG),
                        );
                    });

                // 包含/排除切换
                ui.add_space(8.0);
                let included    = self.hierarchy[sel_idx].included;
                let toggle_txt  = if included { "⊖ 从 XPath 中排除此节点" } else { "⊕ 将此节点加入 XPath" };
                let toggle_color = if included { C_ERR } else { C_OK };
                if ui.add(action_btn(toggle_txt, 0.0, toggle_color)).clicked() {
                    self.hierarchy[sel_idx].included = !included;
                    self.xpath_source = XPathSource::AutoGenerated;
                    self.rebuild_xpath();
                }
                ui.add_space(8.0);
            });
    }

    fn draw_window_properties(&mut self, ui: &mut Ui) {
        panel_header(ui, "⚙  窗口属性过滤器");

        ScrollArea::vertical()
            .id_salt("window_prop_scroll")
            .auto_shrink([false; 2])
            .show(ui, |ui| {
                // 仅在未初始化时才初始化（不在每帧 draw 里判断 is_empty）
                if !self.window_filters_initialized && self.window_info.is_some() {
                    self.init_window_filters();
                }

                if self.window_info.is_none() {
                    ui.add_space(24.0);
                    ui.label(RichText::new("← 请先捕获元素以获取窗口信息").color(C_MUTED).italics());
                    return;
                }

                egui::Frame::NONE
                    .fill(C_PANEL_HDR)
                    .inner_margin(Margin::symmetric(4, 2))
                    .stroke(Stroke::new(0.5, C_BORDER))
                    .show(ui, |ui| {
                        ui.horizontal(|ui| {
                            ui.add_space(22.0);
                            col_label(ui, "属性名", 100.0);
                            col_label(ui, "运算符",  80.0);
                            col_label(ui, "值",       0.0);
                        });
                    });

                ui.add_space(2.0);

                let filter_count = self.window_filters.len();
                let mut dirty = false;
                for fi in 0..filter_count {
                    let row_color = if fi % 2 == 0 {
                        Color32::from_rgb(252, 252, 255)
                    } else {
                        Color32::from_rgb(245, 247, 253)
                    };

                    egui::Frame::NONE
                        .fill(row_color)
                        .inner_margin(Margin::symmetric(4, 1))
                        .show(ui, |ui| {
                            let filter = &mut self.window_filters[fi];
                            ui.horizontal(|ui| {
                                if ui.checkbox(&mut filter.enabled, "").changed() { dirty = true; }

                                ui.add_sized(
                                    Vec2::new(100.0, 20.0),
                                    egui::Label::new(RichText::new(&filter.name.clone()).size(12.0)),
                                );

                                let old_op = filter.operator.clone();
                                egui::ComboBox::from_id_salt(format!("win_op_{}", fi))
                                    .selected_text(filter.operator.label())
                                    .width(76.0)
                                    .show_ui(ui, |ui| {
                                        for op in Operator::all() {
                                            ui.selectable_value(&mut filter.operator, op.clone(), op.label());
                                        }
                                    });
                                if filter.operator != old_op { dirty = true; }

                                if ui.add(
                                    TextEdit::singleline(&mut filter.value)
                                        .desired_width(ui.available_width() - 4.0)
                                        .font(egui::TextStyle::Monospace)
                                        .hint_text("—"),
                                ).changed() {
                                    filter.enabled = !filter.value.is_empty();
                                    dirty = true;
                                }
                            });
                        });
                }

                if dirty {
                    self.custom_window_xpath = true;
                    self.rebuild_window_selector();
                }

                ui.add_space(8.0);
                ui.separator();
                ui.add_space(4.0);

                ui.label(RichText::new("窗口选择器:").color(C_MUTED).size(11.0));
                ui.add_space(2.0);
                egui::Frame::NONE
                    .fill(Color32::from_rgb(248, 250, 252))
                    .stroke(Stroke::new(0.5, C_BORDER))
                    .corner_radius(CornerRadius::same(4))
                    .inner_margin(Margin::symmetric(8, 4))
                    .show(ui, |ui| {
                        ui.label(
                            RichText::new(&self.window_selector)
                                .font(egui::FontId::monospace(11.0))
                                .color(C_MONO_FG),
                        );
                    });
            });
    }

    /// 校验详情（失败时展示逐段分析）
    fn draw_validation_details(&self, ui: &mut Ui) {
        let Some(detail) = &self.detailed_validation else { return };

        ui.add_space(12.0);
        ui.separator();
        ui.add_space(8.0);

        panel_header(ui, "🔍 校验结果");
        ui.add_space(4.0);

        let (status_color, status_text) = match &detail.overall {
            ValidationResult::Found { count, .. } =>
                (C_OK, format!("✓ 通过 — 找到 {} 个元素", count)),
            ValidationResult::NotFound =>
                (C_ERR, "✗ 未找到匹配元素".to_string()),
            ValidationResult::Error(e) =>
                (Color32::from_rgb(200, 100, 0), format!("⚠ 错误: {}", e)),
            _ =>
                (C_MUTED, "未校验".to_string()),
        };

        let frame_fill = if detail.overall == ValidationResult::NotFound {
            Color32::from_rgb(255, 245, 245)
        } else {
            Color32::from_rgb(245, 255, 245)
        };

        egui::Frame::NONE
            .fill(frame_fill)
            .corner_radius(CornerRadius::same(4))
            .inner_margin(Margin::symmetric(10, 6))
            .show(ui, |ui| {
                ui.label(RichText::new(status_text).color(status_color).strong().size(13.0));
                ui.add_space(4.0);
                ui.label(RichText::new(format!("用时: {}ms", detail.total_duration_ms)).color(C_MUTED).size(11.0));
            });

        if detail.overall != ValidationResult::NotFound { return; }

        ui.add_space(8.0);
        ui.label(RichText::new("失败步骤分析:").color(C_MUTED).size(11.0));
        ui.add_space(4.0);

        for seg in &detail.segments {
            if seg.matched || seg.match_count > 0 { continue; }

            egui::Frame::NONE
                .fill(Color32::from_rgb(255, 250, 240))
                .corner_radius(CornerRadius::same(4))
                .inner_margin(Margin::symmetric(8, 6))
                .show(ui, |ui| {
                    ui.label(
                        RichText::new(format!("第 {} 步失败:", seg.segment_index + 1))
                            .color(Color32::from_rgb(200, 100, 0))
                            .size(11.0),
                    );
                    ui.add_space(2.0);
                    ui.label(
                        RichText::new(&seg.segment_text)
                            .font(egui::FontId::monospace(10.0))
                            .color(C_MONO_FG),
                    );

                    if !seg.predicate_failures.is_empty() {
                        ui.add_space(4.0);
                        for pf in &seg.predicate_failures {
                            ui.horizontal(|ui| {
                                ui.label(RichText::new(format!("{}: ", pf.attr_name)).color(C_MUTED).size(10.0));
                                ui.label(RichText::new(format!("期望 '{}'", pf.expected_value)).color(Color32::from_rgb(100, 100, 200)).size(10.0));
                                if let Some(ref actual) = pf.actual_value {
                                    ui.label(RichText::new(" vs ").color(C_MUTED).size(10.0));
                                    ui.label(RichText::new(format!("实际 '{}'", actual)).color(Color32::from_rgb(200, 100, 100)).size(10.0));
                                }
                            });
                            ui.label(RichText::new(&pf.reason).color(C_MUTED).size(10.0));
                        }
                    } else {
                        ui.label(RichText::new("• 属性值在验证时可能已变化").color(C_MUTED).size(10.0));
                        ui.label(RichText::new("• 元素结构在捕获后可能已变化").color(C_MUTED).size(10.0));
                    }
                });
            ui.add_space(4.0);
        }

        ui.add_space(8.0);
        ui.label(RichText::new("建议:").color(C_MUTED).size(11.0));
        ui.add_space(4.0);
        ui.label(RichText::new("1. 点击【智能优化】按钮，移除动态属性").color(C_MUTED).size(10.0));
        ui.label(RichText::new("2. 检查动态类名是否在捕获后发生了变化").color(C_MUTED).size(10.0));
        ui.label(RichText::new("3. 重新捕获元素，确保元素状态稳定").color(C_MUTED).size(10.0));
    }
}

// ─── eframe::App impl ────────────────────────────────────────────────────────

impl eframe::App for SelectorApp {
    fn save(&mut self, storage: &mut dyn eframe::Storage) {
        self.config.last_xpaths = self.history.clone();
        if let Ok(json) = serde_json::to_string(&self.config) {
            storage.set_string("app_config", json);
        }
        if !self.hierarchy.is_empty() {
            let data = self.build_persisted_capture();
            if let Ok(json) = serde_json::to_string(&data) {
                storage.set_string("last_capture", json);
            }
        }
    }

    fn ui(&mut self, ui: &mut Ui, _frame: &mut eframe::Frame) {
        // 捕获状态下持续刷新
        if self.capture_state != CaptureState::Idle {
            ui.ctx().request_repaint_after(Duration::from_millis(200));
        }

        // ── 全局键盘 ─────────────────────────────────────────────────────────
        let (f4, f7, escape) = ui.ctx().input(|i| {
            (i.key_pressed(Key::F4), i.key_pressed(Key::F7), i.key_pressed(Key::Escape))
        });
        if f4 && self.capture_state == CaptureState::Idle { self.start_capture(); }
        if f7 { self.do_validate(); }

        // ── 捕获等待逻辑 ──────────────────────────────────────────────────────
        if let CaptureState::WaitingClick { deadline } = &self.capture_state {
            if Instant::now() > *deadline {
                // 超时
                highlight::hide();
                mouse_hook::deactivate_capture();
                self.overlay.hide();
                self.capture_state = CaptureState::Idle;
                self.status_msg    = "捕获超时，已取消".to_string();
                ui.ctx().set_cursor_icon(egui::CursorIcon::Default);
            } else if escape {
                self.cancel_capture(ui.ctx());
            } else if let Some(event) = mouse_hook::poll_click() {
                if event.is_down {
                    let mode = event.capture_mode();
                    if mode != CaptureMode::None {
                        self.finish_capture_at(event.x, event.y, mode, ui.ctx());
                    }
                }
            }

            // 悬停高亮（防抖 500ms）
            let (mx, my, mt) = mouse_hook::get_mouse_state();
            if mt > 0 {
                let now_ms = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_millis() as u64;
                if now_ms.saturating_sub(mt) >= 500 {
                    if self.last_highlight_pos != Some((mx, my)) {
                        self.highlight_element_at(mx, my);
                        self.last_highlight_pos = Some((mx, my));
                    }
                } else {
                    self.last_highlight_pos = None;
                }
            }
        } else {
            highlight::hide();
            self.last_mouse_move    = None;
            self.last_highlight_pos = None;
        }

        self.overlay.draw(ui.ctx());

        // ── 全局样式 ──────────────────────────────────────────────────────────
        ui.ctx().set_global_style({
            let mut s = (*ui.ctx().global_style()).clone();
            s.visuals.panel_fill   = Color32::WHITE;
            s.visuals.window_fill  = Color32::WHITE;
            s.spacing.item_spacing = egui::vec2(4.0, 2.0);
            s.spacing.window_margin     = egui::Margin::same(0);
            s.spacing.button_padding    = egui::vec2(6.0, 3.0);
            s.spacing.indent            = 14.0;
            s.spacing.interact_size     = egui::vec2(18.0, 18.0);
            s.visuals.widgets.noninteractive.bg_stroke = Stroke::new(1.0, C_DIVIDER);
            s
        });

        // ── Panel 布局 ────────────────────────────────────────────────────────
        self.draw_titlebar(ui);
        self.draw_top_bar(ui);
        self.draw_capture_banner(ui);   // 仅捕获状态下可见
        self.draw_bottom_panel(ui);     // XPath 预览 + 状态 + 确定/取消（单一 Panel）

        egui::CentralPanel::default()
            .frame(Frame::NONE.fill(Color32::from_gray(250)))
            .show_inside(ui, |ui| {
                ui.add_space(6.0);

                // ── 标签页 + 辅助开关 ─────────────────────────────────────────
                ui.horizontal(|ui| {
                    let element_active = self.active_tab == ElementTab::Element;
                    let window_active  = self.active_tab == ElementTab::WindowElement;

                    if ui.selectable_label(element_active, RichText::new("元素").size(12.0)).clicked() {
                        self.active_tab = ElementTab::Element;
                    }
                    ui.add_space(4.0);
                    if ui.selectable_label(window_active, RichText::new("窗口元素").size(12.0)).clicked() {
                        self.active_tab = ElementTab::WindowElement;
                    }

                    ui.add_space(16.0);

                    ui.with_layout(Layout::right_to_left(Align::Center), |ui| {
                        // 简化/完整 XPath 切换
                        let simplified_changed = ui.checkbox(&mut self.show_simplified, "简化 XPath")
                            .on_hover_text("切换简化模式与完整属性模式")
                            .changed();
                        if simplified_changed && self.xpath_source.is_auto() {
                            self.rebuild_xpath();
                        }
                    });
                });

                ui.separator();

                // ── 两列分割布局（可拖拽分隔线）────────────────────────────────
                const DIVIDER_W:   f32 = 1.0;
                const DRAG_ZONE_W: f32 = 5.0;
                const GAP:         f32 = 8.0;
                const LEFT_MIN:    f32 = 220.0;

                let full_rect = ui.available_rect_before_wrap();
                let left_max  = 0.9 * full_rect.width();
                let left_w    = self.left_panel_width.clamp(LEFT_MIN, left_max);
                let div_x     = full_rect.min.x + left_w;

                let left_rect = egui::Rect::from_min_max(
                    full_rect.min,
                    egui::pos2(div_x - GAP, full_rect.max.y),
                );
                let right_rect = egui::Rect::from_min_max(
                    egui::pos2(div_x + GAP, full_rect.min.y),
                    full_rect.max,
                );

                // 拖拽区域
                let drag_rect = egui::Rect::from_center_size(
                    egui::pos2(div_x, full_rect.center().y),
                    egui::vec2(DRAG_ZONE_W * 2.0, full_rect.height()),
                );
                let drag_id   = egui::Id::new("panel_divider_drag");
                let drag_resp = ui.interact(drag_rect, drag_id, Sense::drag());

                if drag_resp.dragged() {
                    self.divider_dragging = true;
                    self.left_panel_width =
                        (self.left_panel_width + drag_resp.drag_delta().x)
                            .clamp(LEFT_MIN, left_max);
                }
                if drag_resp.drag_stopped() {
                    self.divider_dragging = false;
                }
                if drag_resp.hovered() || self.divider_dragging {
                    ui.ctx().set_cursor_icon(egui::CursorIcon::ResizeHorizontal);
                }

                // 分隔线
                let line_color = if self.divider_dragging { C_SEL_FG } else { C_BORDER };
                ui.painter().line_segment(
                    [
                        egui::pos2(div_x, full_rect.min.y),
                        egui::pos2(div_x, full_rect.max.y),
                    ],
                    Stroke::new(DIVIDER_W, line_color),
                );

                // 左栏
                ui.painter().rect_filled(left_rect, 0.0, Color32::WHITE);
                let left_content = left_rect.shrink2(egui::vec2(6.0, 4.0));
                let mut left_ui  = ui.new_child(
                    egui::UiBuilder::new()
                        .max_rect(left_content)
                        .layout(egui::Layout::top_down(egui::Align::Min)),
                );
                left_ui.set_clip_rect(left_rect);
                self.draw_left_panel(&mut left_ui);

                // 右栏
                ui.painter().rect_filled(right_rect, 0.0, Color32::WHITE);
                let right_content = right_rect.shrink2(egui::vec2(8.0, 4.0));
                let mut right_ui  = ui.new_child(
                    egui::UiBuilder::new()
                        .max_rect(right_content)
                        .layout(egui::Layout::top_down(egui::Align::Min)),
                );
                right_ui.set_clip_rect(right_rect);
                self.draw_right_panel(&mut right_ui);
            });
    }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

fn panel_header(ui: &mut Ui, title: &str) {
    let w = ui.available_width();
    Frame::NONE
        .fill(C_PANEL_HDR)
        .inner_margin(Margin::symmetric(8, 3))
        .stroke(Stroke::new(0.5, C_BORDER))
        .show(ui, |ui| {
            ui.set_max_width(w);
            ui.label(RichText::new(title).color(Color32::from_gray(70)).size(11.5).strong());
        });
    ui.add_space(2.0);
}

fn col_label(ui: &mut Ui, text: &str, width: f32) {
    if width > 0.0 {
        ui.add_sized(
            Vec2::new(width, 16.0),
            egui::Label::new(RichText::new(text).color(C_MUTED).size(10.5).strong()),
        );
    } else {
        ui.label(RichText::new(text).color(C_MUTED).size(10.5).strong());
    }
}

fn action_btn(label: &str, width: f32, color: Color32) -> egui::Button<'static> {
    let b = egui::Button::new(RichText::new(label.to_string()).size(11.5).color(color));
    if width > 0.0 { b.min_size(Vec2::new(width, 26.0)) } else { b }
}

fn prop_row(ui: &mut Ui, key: &str, val: &str) {
    ui.horizontal(|ui| {
        ui.label(RichText::new(key).color(C_MUTED).size(10.5).monospace());
        ui.add_space(6.0);
        ui.label(RichText::new(val).color(Color32::from_gray(35)).size(10.5).monospace());
    });
    ui.add_space(2.0);
}

fn node_tooltip(ui: &mut Ui, node: &HierarchyNode) {
    ui.label(RichText::new("元素详情").strong().size(11.0));
    ui.separator();
    for (k, v) in [
        ("ControlType",  node.control_type.as_str()),
        ("AutomationId", node.automation_id.as_str()),
        ("ClassName",    node.class_name.as_str()),
        ("Name",         node.name.as_str()),
    ] {
        ui.horizontal(|ui| {
            ui.label(RichText::new(k).color(C_MUTED).size(10.0));
            ui.add_space(4.0);
            ui.label(RichText::new(v).monospace().size(10.0));
        });
    }
    if node.rect.width > 0 {
        ui.label(
            RichText::new(format!(
                "Rect {}×{}  @({},{})",
                node.rect.width, node.rect.height, node.rect.x, node.rect.y,
            ))
            .size(10.0)
            .color(C_MUTED),
        );
    }
}

/// RichText 扩展：条件加粗
trait RichTextExt {
    fn strong_if(self, cond: bool) -> Self;
}
impl RichTextExt for RichText {
    fn strong_if(self, cond: bool) -> Self {
        if cond { self.strong() } else { self }
    }
}

/// 截断字符串（预留功能）
#[allow(dead_code)]
fn truncate_str(s: &str, max_chars: usize) -> String {
    let mut cs = s.chars();
    let collected: String = cs.by_ref().take(max_chars).collect();
    if cs.next().is_some() { format!("{}…", collected) } else { collected }
}
