// src/gui/types.rs
//
// 应用内部使用的枚举和数据结构

use serde::{Deserialize, Serialize};

// 重导出 CaptureMode 从 core::model
pub use element_selector::core::model::CaptureMode;

/// XPath 来源状态（替代双重 bool 标志）
#[derive(Debug, Clone)]
pub enum XPathSource {
    /// 由层级结构自动生成
    AutoGenerated,
    /// 经过智能优化，携带摘要信息
    Optimized(element_selector::core::OptimizationSummary),
    /// 用户手动编辑
    Manual,
}

impl XPathSource {
    pub fn optimization_summary(&self) -> Option<&element_selector::core::OptimizationSummary> {
        if let XPathSource::Optimized(s) = self { Some(s) } else { None }
    }
}

/// TypeScript 代码格式
#[derive(Debug, Clone, PartialEq)]
pub enum CodeFormat {
    /// 完整链式调用: sdk.flow().window({...}).find('xpath')
    /// 适用场景：从头开始编写新脚本
    FullChain,
    /// 参数对象: { window: {...}, xpath: '...' }
    /// 适用场景：在已有代码中插入新步骤
    ParamsObject,
    /// 仅 XPath 字符串: 'xpath'
    /// 适用场景：快速复制 XPath 用于其他用途
    XPathOnly,
}

impl std::fmt::Display for CodeFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodeFormat::FullChain => write!(f, "完整链式调用"),
            CodeFormat::ParamsObject => write!(f, "参数对象"),
            CodeFormat::XPathOnly => write!(f, "仅 XPath"),
        }
    }
}

/// 捕获状态
#[derive(Debug, PartialEq)]
pub enum CaptureState {
    Idle,
    WaitingClick { deadline: std::time::Instant },
    Capturing,
}

/// 持久化捕获数据
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersistedCapture {
    pub hierarchy:              Vec<element_selector::core::model::HierarchyNode>,
    pub selected_node:          Option<usize>,
    pub xpath_text:             String,
    pub window_info:            Option<element_selector::core::model::WindowInfo>,
    /// 窗口过滤器状态
    pub window_filters_enabled: Vec<bool>,
    /// XPath 来源类型
    pub xpath_source_kind:      String,  // "Auto", "Optimized", "Manual"
    /// 优化摘要（如果有）
    pub optimization_summary:   Option<OptimizationSummaryPersisted>,
    /// 结果序号（选择第N个匹配元素）
    pub result_index:           Option<String>,
    /// 捕获模式（快速捕获 vs 增强捕获）
    #[serde(default)]
    pub capture_mode:           Option<CaptureMode>,
}

/// 优化摘要持久化格式
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimizationSummaryPersisted {
    pub removed_dynamic_attrs: usize,
    pub simplified_attrs:      usize,
    pub used_anchor:           bool,
}
